config/routes.rb
Rails.application.routes.draw do

  get 'searchs/search'
  get 'search/search'
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about" , as: "about"
  resources :users, only:[:edit, :update, :show, :index] do
    resource :relationships, only:[:create, :destroy]
    get "/follows" => 'relationships#follower', as: 'follows'
    get "/followers" => 'relationships#followed', as: 'followers'
  end
  resources :books, only:[:index, :show, :create, :update, :destroy, :edit] do
    resources :book_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end

  get 'search' => 'searchs#search', as: 'search'
  resources :messages, :only => [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum:200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def Book.search(search,keyword)
    if search == 'perfect_match'
      @book = Book.where("title LIKE?","#{keyword}")
    elsif search == 'partial_match'
      @book = Book.where("title LIKE(?)","%#{keyword}%")
    elsif search == 'forward_match'
      @book = Book.where("title LIKE(?)","#{keyword}%")
    elsif search == 'backward_match'
      @book = Book.where("title LIKE(?)","%#{keyword}")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy#ユーザとフォローいている人の紐付け
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy#ユーザとフォローされている人の紐付け
  has_many :following_user, through: :follower, source: :followed#自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower#自分がフォローされている人

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  def follow(user_id)#フォローする
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)#フォローを外す
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def User.search(search,keyword)
    if search == 'perfect_match'
      @user = User.where("name LIKE?","#{keyword}")
    elsif search == 'partial_match'
      @user = User.where("name LIKE(?)","%#{keyword}%")
    elsif search == 'forward_match'
      @user = User.where("name LIKE(?)","#{keyword}%")
    elsif search == 'backward_match'
      @user = User.where("name LIKE(?)","%#{keyword}")
    else
      @user = User.all
    end
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  def prefecture_name=(prefecture_name)
    self.prefecture_code=JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  attachment :profile_image

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all #投稿情報を全て取得
    @book = Book.new #新規投稿を保存する #バリデーション@bookの部分？
  end

  def show
    @book = Book.find(params[:id]) #本の名前タイトルなど引っ張ってくるため
    @book_new = Book.new #新規投稿画面に何も表示させなくするため（部分テンプレート）
    @user = @book.user #showから部分テンプレート（info）を呼び出すときに使う
    @book_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params) #入力されたデータが@bookに入る
    @book.user_id = current_user.id #投稿とユーザ情報の紐付け
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all #本の一覧画面表示させるため?　部分テンプレートじゃないところ
      @user = current_user #user info表示のため　部分テンプレートで使用しているため
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id]) #本の編集画面に情報を表示させるため
    if @book.user.id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private #ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all #一覧を表示するためall
    @book = Book.new #部分テンプレート(books/form)
    @user = current_user #部分テンプレート(uses/info)
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new #部分テンプレート(books/form)
    @books = @user.books #ユーザが投稿した本の
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<!--新規投稿-->
<!--users/index,show @book=Book.new-->
<h2>New book</h2>
<%= form_with model:book, local:true, class:"new-form" do |f| %>
  <p>Title</p>
    <%= f.text_field :title, class:"new-form-text" %>
  <p>Opinion</p>
    <%= f.text_area :body, class:"new-form-text" %>
    <%= f.submit "Create Book", class:"btn btn-success new-btn" %>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover">
  <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th></th>
    <th></th>
  </tr>
  <% books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill,50,50, fallback: "no_image.jpg", size: "50x50" %>
        <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
      <td id="favorite-btn_<%= book.id %>" >
        <%= render 'favorites/favorite', book: book %>
      </td>
      <td>
        <%= render 'book_comments/count', book: book %>
      </td>
    </tr>
  <% end %>
</table>

app/views/books/edit.html.erb
<h1 class="edit-header">Editing Book</h1>

<!--バリデーション-->
<div class="edit-error-msg">
  <% if @book.errors.any? %>
    <%= @book.errors.count %>errors
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
</div>

<!--本の投稿編集画面-->
<%= form_with model:@book, local:true, class:"form" do |f| %>
  <p>Title</p>
  <%= f.text_field :title, class:"form-text" %>
  <p>Opinion</p>
  <%= f.text_area :body, class:"form-text" %>
  <%= f.submit "Update Book", class:"btn btn-success" %>
<% end %>
<div class="btn-wrapper">
  <%= link_to "Show", book_path(@book.id), class:"inline-block" %>
  <p class="inline-block">|</p>
  <%= link_to "Back", books_path, class:"inline-block" %>
</div>

app/views/books/index.html.erb
<div class="container">
  <!--バリデーション-->
  <div class="row new-error-msg">
    <% if @book.errors.any? %>
      <%= @book.errors.count %>error
      <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
  </div>

  <div class="row">
    <!--左側（部分テンプレート）-->
    <div class="col-md-3">
      <%= render 'users/info', user: current_user %>
      <%= render 'books/form', book: @book %>
    </div>

    <!--右側-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <!--左側（部分テンプレート）-->
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/form', book: @book_new %>
    </div>

    <!--右側-->
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <td id="favorite-btn_<%= @book.id %>" >
            <%= render 'favorites/favorite', book: @book %>
          </td>
          <td id='book-comment-count_<%= @book.id %>'>
            <%= render 'book_comments/count', book: @book %>
          </td>
          <% if @book.user_id == current_user.id %>
          <td><%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-success btn-sm" %></td>
          <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-danger btn-sm" %></td>
          <% end %>
        </tr>
      </table>

      <!--コメント一覧-->
      <div id="book-comment_<%= @book.id %>">
        <%= render 'book_comments/book_comment', book: @book %>
      </div>
      <!--コメント入力フォーム-->
      <%= form_with(model: [@book, @book_comment], remote: true) do |f|%>
        <%= f.text_area :comment, size:"90x5" %>
        <%= f.submit '送信' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_index.html.erb
<table class="table">
  <tr>
    <th>image</th>
    <th>name</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %></td>
      <td><%= user.name %></td>
      <td><p>フォロー数：<%= user.following_user.count %></p></td>
      <td><p>フォロワー数：<%= user.follower_user.count %></p></td>
      <td>
        <% if current_user != user %>
          <% if current_user.following?(user) %>
            <%= link_to 'フォローを外す', user_relationships_path(user), method: :delete %>
          <% else %>
            <%= link_to 'フォローする', user_relationships_path(user), method: :post %>
          <% end %>
        <% end %>
      </td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
  <% end %>
</table>

app/views/users/_info.html.erb
<!--ユーザ情報-->
<!--index user=currentuser-->
<!--show user=user.book-->
<div class="user-info">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill,100,100, fallback: "no_image.jpg", size: "100x100", class:"user-image", id: "img_prev" %>
  <table class="table">
    <tr>
      <th><p>name</p></th>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <th><p>introduction</p></th>
      <td><%= user.introduction %></td>
    </tr>
    <tr>
      <th><p>follows</p></th>
      <td><%= link_to user.following_user.count, user_follows_path(user) %></td>
    </tr>
    <tr>
      <th><p>followers</p></th>
      <td><%= link_to user.follower_user.count, user_followers_path(user) %></td>
    </tr>
  </table>
  <% if user.id == current_user.id %>
    <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary user-custom" do %>
    <span><i class="fas fa-user-cog"></i></span>
    <% end %>
  <% else %>
    <% if current_user.following?(user) %>
      <%= link_to 'フォローを外す', user_relationships_path(user), method: :delete, class:"btn btn-info" %>
    <% else %>
      <%= link_to 'フォローする', user_relationships_path(user), method: :post, class:"btn btn-success" %>
    <% end %>
  <% end %><br>

  <% if current_user != user %>
    <%= link_to 'chatを始める', message_path(user.id)%>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2 class="edit-header">User info</h2>

<!--バリデーション-->
<div class="edit-error-msg">
  <% if @user.errors.any? %>
    <%= @user.errors.count %>errors
    <% @user.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
</div>

<%= form_with model:@user, local:true, class:"form" do |f| %>
  <p>Name</p>
    <%= f.text_field :name, class:"form-text"  %>
  <p>Image</p>
    <%= f.attachment_field :profile_image %>
  <p>Introduction</p>
    <%= f.text_area :introduction, class:"form-text"  %>
    <%= f.submit "Update User", class:"btn btn-secondary" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <!--左側（部分テンプレート）-->
    <div class="col-md-3">
      <%= render 'users/info', user: current_user %>
      <%= render 'books/form', book: @book %>
    </div>

    <!--右側-->
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'users/index', users: @users %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

    <!--左側（部分テンプレート）-->
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>

    <!--右側-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <% @books.each do |book|%>
          <tr>
            <%= link_to user_path(book.user.id) do %>
              <td><%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %></td>
            <% end %>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </table>
    </div>

  </div>
</div>