config/routes.rb
Rails.application.routes.draw do

  get 'searchs/search'
  get 'search/search'
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about" , as: "about"
  resources :users, only:[:edit, :update, :show, :index] do
    resource :relationships, only:[:create, :destroy]
    get "/follows" => 'relationships#follower', as: 'follows'
    get "/followers" => 'relationships#followed', as: 'followers'
  end
  resources :books, only:[:index, :show, :create, :update, :destroy, :edit] do
    resources :book_comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
  end

  get 'search' => 'searchs#search', as: 'search'
  resources :messages, :only => [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum:200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def Book.search(search,keyword)
    if search == 'perfect_match'
      @book = Book.where("title LIKE?","#{keyword}")
    elsif search == 'partial_match'
      @book = Book.where("title LIKE(?)","%#{keyword}%")
    elsif search == 'forward_match'
      @book = Book.where("title LIKE(?)","#{keyword}%")
    elsif search == 'backward_match'
      @book = Book.where("title LIKE(?)","%#{keyword}")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy#ユーザとフォローいている人の紐付け
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy#ユーザとフォローされている人の紐付け
  has_many :following_user, through: :follower, source: :followed#自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower#自分がフォローされている人

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  def follow(user_id)#フォローする
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)#フォローを外す
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def User.search(search,keyword)
    if search == 'perfect_match'
      @user = User.where("name LIKE?","#{keyword}")
    elsif search == 'partial_match'
      @user = User.where("name LIKE(?)","%#{keyword}%")
    elsif search == 'forward_match'
      @user = User.where("name LIKE(?)","#{keyword}%")
    elsif search == 'backward_match'
      @user = User.where("name LIKE(?)","%#{keyword}")
    else
      @user = User.all
    end
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  def prefecture_name=(prefecture_name)
    self.prefecture_code=JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  attachment :profile_image

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all #投稿情報を全て取得
    @book = Book.new #新規投稿を保存する #バリデーション@bookの部分？
  end

  def show
    @book = Book.find(params[:id]) #本の名前タイトルなど引っ張ってくるため
    @book_new = Book.new #新規投稿画面に何も表示させなくするため（部分テンプレート）
    @user = @book.user #showから部分テンプレート（info）を呼び出すときに使う
    @book_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params) #入力されたデータが@bookに入る
    @book.user_id = current_user.id #投稿とユーザ情報の紐付け
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all #本の一覧画面表示させるため?　部分テンプレートじゃないところ
      @user = current_user #user info表示のため　部分テンプレートで使用しているため
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id]) #本の編集画面に情報を表示させるため
    if @book.user.id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private #ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="text-center mt-5">
  <p>CopyRight Infratop.inc</p>
</div>

app/views/layouts/_header.html.erb
<div class="d-block p-2 bg-dark text-white mb-3">

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <!--ヘッダー左側-->
      <span class="navbar-brand mr-auto"><%= link_to "Bookers", root_path, class:'nav-link text-light' %></span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></i></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

      <!--ヘッダー右側-->
      <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to user_path(current_user), class: 'nav-link text-light' do  %>
            <span><i class="fas fa-home"></i>Home</span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to users_path, class: 'nav-link text-light' do %>
            <span><i class="fas fa-users">Users</i></span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to books_path, class: 'nav-link text-light' do %>
            <span><i class="fas fa-book-open">Books</i></span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
            <span><i class="fas fa-sign-out-alt">logout</i></span>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to root_path, class: 'nav-link text-light' do %>
            <span><i class="fas fa-home"></i>Home</span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to about_path, class: 'nav-link text-light' do %>
            <span><i class="fas fa-link"></i>About</span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
            <span><i class="fas fa-user-plus"></i>Sign up</span>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
            <span><i class="fas fa-sign-in-alt"></i>Login</span>
          <% end %>
        </li>
      <% end %>
      </ul>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/51b68fc5d8.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <%= render 'searchs/form' %>
    <!--サクセスメッセージ-->
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key} msg") %>
    <% end %>

    <!--各ビュー-->
    <%= yield %>

    <footer class="text-center mt-5">
      <%= render 'layouts/footer' %>
    </footer>

  </body>
</html>